name: Build and deploy Node.js app to Azure Web App - presspay-api

on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubbutu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          npm install
      - name: Deploy to AAS
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'presspay-api'
          publish-profile: ${{secrets.AZURE_WEBAPP_PUBLISH_PROFILE}}
          package: .


          